'use client';
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Textarea} from '@/components/ui/textarea';
type Revision={id:string;label:string;summary:string;url:string};
export type Photo={id:string;title:string;editable:boolean;credit:string;source:string;revisions:Revision[]};
type Comment={id:string;photo_id:string;revision_id:string;text:string;created:number};
function Picture({revision,accessKey,small=false}:{revision:Revision;accessKey:string;small?:boolean}){
 const [url,setUrl]=useState(revision.url.startsWith('https:')?revision.url:''),[error,setError]=useState(false);
 useEffect(()=>{if(revision.url.startsWith('https:')){setUrl(revision.url);return;}let dead=false,object='';setUrl('');setError(false);fetch(revision.url,{headers:{Authorization:'Bearer '+accessKey}}).then(async r=>{if(!r.ok)throw Error();return r.blob();}).then(blob=>{object=URL.createObjectURL(blob);if(!dead)setUrl(object);else URL.revokeObjectURL(object);}).catch(()=>{if(!dead)setError(true);});return()=>{dead=true;if(object)URL.revokeObjectURL(object);};},[revision.url,accessKey]);
 return error?<span className="image-wait">Photo could not load</span>:url?<img src={url} alt={revision.label+': '+revision.summary} className={small?'thumb-image':'main-image'} onError={()=>setError(true)}/>:<span className="image-wait">{error?'Photo could not load':'Loading photo…'}</span>;
}
export default function Gallery({photos,comments,accessKey,onPhoto,refresh}:{photos:Photo[];comments:Comment[];accessKey:string;onPhoto:(id:string,revision:string)=>void;refresh:()=>Promise<void>}){
 const [photoId,setPhotoId]=useState(''),[revisionId,setRevisionId]=useState(''),[draft,setDraft]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState('');
 const photo=photos.find(p=>p.id===photoId)||photos[0],revision=photo?.revisions.find(r=>r.id===revisionId)||photo?.revisions.at(-1),index=photos.findIndex(p=>p.id===photo?.id);
 useEffect(()=>{setPhotoId(new URLSearchParams(location.search).get('photo')||'');},[]);
 useEffect(()=>{if(photo&&revision)onPhoto(photo.id,revision.id);},[photo?.id,revision?.id,onPhoto]);
 if(!photo||!revision)return null;
 function select(id:string){if(saving)return;setPhotoId(id);setRevisionId('');setDraft('');setError('');const url=new URL(location.href);url.searchParams.set('photo',id);history.replaceState(null,'',url);}
 async function comment(e:React.FormEvent){e.preventDefault();if(!draft.trim()||saving)return;setSaving(true);setError('');try{const r=await fetch('/api/comments',{method:'POST',headers:{Authorization:'Bearer '+accessKey,'Content-Type':'application/json'},body:JSON.stringify({id:crypto.randomUUID(),photo_id:photo.id,revision_id:revision!.id,text:draft})});if(!r.ok){const d=await r.json() as {error:string};throw Error(d.error);}setDraft('');await refresh();}catch(e){setError(e instanceof Error?e.message:'Could not save comment.');}finally{setSaving(false);}}
 return <section className="gallery"><nav className="photo-strip" aria-label="Choose a photo">{photos.map(p=><button key={p.id} onClick={()=>select(p.id)} className={p.id===photo.id?'selected':''} aria-pressed={p.id===photo.id}><Picture revision={p.revisions.at(-1)!} accessKey={accessKey} small/><span>{p.title}</span></button>)}</nav><div className="gallery-heading"><Button variant="outline" disabled={index===0} onClick={()=>select(photos[index-1].id)}>← Previous</Button><div><h2>{photo.title}</h2><p>{index+1} of {photos.length} · {revision.label}</p></div><Button variant="outline" disabled={index===photos.length-1} onClick={()=>select(photos[index+1].id)}>Next →</Button></div><div className="photo-stage"><Picture revision={revision} accessKey={accessKey}/></div><div className="photo-caption"><p>{revision.summary}</p><span>{photo.source?<a href={photo.source} target="_blank" rel="noreferrer">{photo.credit}</a>:photo.credit}</span></div><h3>Revisions</h3><div className="revision-strip">{photo.revisions.map(r=><button key={r.id} className={r.id===revision.id?'selected':''} aria-pressed={r.id===revision.id} disabled={saving} onClick={()=>{setRevisionId(r.id);setDraft('');}}><Picture revision={r} accessKey={accessKey} small/><strong>{r.label}</strong></button>)}</div>{!photo.editable&&<p className="note">Comments are open. Automated Lightroom edits are not connected for this photo yet.</p>}<div className="comments"><h3>Comments on this photo</h3><form onSubmit={comment}><label htmlFor="comment">Comment on {revision.label}</label><Textarea id="comment" disabled={saving} value={draft} onChange={e=>setDraft(e.target.value)} maxLength={2000} required rows={3} placeholder="What do you think of this version?"/><Button type="submit" disabled={saving||!draft.trim()}>{saving?'Saving…':'Add comment'}</Button><p className="note">Comments stay with the selected version. They don’t start an edit.</p>{error&&<p role="alert" className="error">{error}</p>}</form>{comments.filter(c=>c.photo_id===photo.id).map(c=><article key={c.id}><div className="heading"><strong>Reviewer</strong><span>{photo.revisions.find(r=>r.id===c.revision_id)?.label} · {new Date(c.created).toLocaleString()}</span></div><p>{c.text}</p></article>)}{!comments.some(c=>c.photo_id===photo.id)&&<p className="note">No comments yet.</p>}</div></section>;
}
