import {createBoothScene} from '/booth-scene.js';
const $=id=>document.getElementById(id), base=location.pathname.replace(/\/$/,''), scene=createBoothScene($('booth'));
const delay=Math.min(12,Math.max(0,Number(new URLSearchParams(location.search).get('delay')??4)||0));
let state={decks:[],crate:[]},frames=[],seen=['',''],hls=null,lastRequests='',playing=false;
async function api(path,options){const r=await fetch(base+'/api/'+path,options);if(!r.ok){let error;try{error=(await r.json()).detail;}catch{}throw Error(typeof error==='string'?error:'The DJ is temporarily offline.');}return r.json();}
function display(next){state=next;state.decks.forEach((d,i)=>{if(d.id&&d.id!==seen[i]){scene.onTrackLoaded(i,d);seen[i]=d.id;}});const active=state.decks.filter(d=>d.playing).sort((a,b)=>(b.fade??1)*(b.level??1)-(a.fade??1)*(a.level??1));const track=active[0];$('now-title').textContent=track?.title||'Waiting for the DJ';$('now-artist').textContent=track?.artist||'Make yourself comfortable.';$('set-tempo').textContent=state.tempo?`${state.tempo} BPM · live set`:'Live set';}
function animate(){const now=performance.now();while(frames.length&&frames[0].at<=now)display(frames.shift().state);scene.update(state);requestAnimationFrame(animate);}animate();
async function poll(){try{const next=await api('state');frames.push({at:performance.now()+delay*1000,state:next});if(frames.length>40)frames.shift();$('connection').textContent=next.broadcasting?'Live now':'DJ is getting ready';$('connection').classList.toggle('live',!!next.broadcasting);}catch{$('connection').textContent='Reconnecting…';$('connection').classList.remove('live');}setTimeout(poll,500);}poll();
function row(record){const li=document.createElement('li'),title=document.createElement('strong'),meta=document.createElement('div'),name=document.createElement('span'),status=document.createElement('span'),reason=document.createElement('p');title.textContent=record.title||'Checking track';meta.className='request-meta';name.textContent=record.name||'Listener';status.className='status '+record.status;status.textContent=({accepted:'In the queue',added:'Added to the set',dismissed:'Dismissed by DJ',needs_audio:'Needs audio',review:'DJ review',pending:'Waiting',identifying:'Identifying',downloading:'Getting audio',analyzing:'Checking fit',rejected:'Not this set',error:'Could not check'})[record.status]||record.status;reason.textContent=record.reason||'';meta.append(name,status);li.append(title,meta,reason);return li;}
async function requests(){try{const data=await api('requests'),signature=JSON.stringify(data.requests);if(signature!==lastRequests){lastRequests=signature;const list=$('request-list');list.replaceChildren();if(data.requests.length)data.requests.slice(-10).reverse().forEach(r=>list.append(row(r)));else{const empty=document.createElement('li');empty.textContent='No requests yet. Yours can be first.';list.append(empty);}}}catch{}setTimeout(requests,3000);}requests();
$('request-form').addEventListener('submit',async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button');button.disabled=true;$('request-message').textContent='Sending your request…';try{const result=await api('requests',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({url:$('song-url').value,name:$('listener-name').value||'Listener'})});$('request-message').textContent=result.reason||'Request received.';$('song-url').value='';}catch(error){$('request-message').textContent=error.message;}finally{button.disabled=false;}});
$('listen').addEventListener('click',async()=>{const audio=$('audio');if(playing){audio.pause();return;}const url=base+'/live/index.m3u8';$('audio-status').textContent='Connecting to live audio…';audio.hidden=false;try{if(!audio.src&&!hls){if(audio.canPlayType('application/vnd.apple.mpegurl'))audio.src=url;else if(window.Hls?.isSupported()){hls=new Hls({liveSyncDurationCount:2,maxBufferLength:12});hls.loadSource(url);hls.attachMedia(audio);hls.on(Hls.Events.ERROR,(_,data)=>{if(data.fatal){$('audio-status').textContent='Audio is not live yet. Try again when the DJ starts broadcasting.';hls.destroy();hls=null;audio.removeAttribute('src');}});}else throw Error('This browser cannot play this live stream. Try Safari, Chrome or Firefox.');}await audio.play();}catch(error){$('audio-status').textContent=error.name==='NotSupportedError'?'The DJ has not started live audio yet. Try again shortly.':error.message;}});
$('audio').addEventListener('playing',()=>{playing=true;$('listen').textContent='Pause audio';$('audio-status').textContent='You’re listening live.';});$('audio').addEventListener('pause',()=>{playing=false;$('listen').textContent='Listen live ↗';});$('audio').addEventListener('error',()=>{$('audio-status').textContent='Live audio is unavailable. Try again when the DJ is broadcasting.';$('audio').removeAttribute('src');});window.addEventListener('pagehide',()=>{hls?.destroy();scene.dispose();});
